name: Continuous Integration

on:
  push:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fmt check
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose --all
      - name: Run tests
        run: cargo test --verbose --all
      - name: Run clippy
        run: cargo clippy --verbose --all -- -D warnings
